name: Quant Search operations
description: Perform operations against a Quant Search index
author: QuantCDN
inputs:
  customer:
    description: Your customer account name
    required: true
  project:
    description: Your project name
    required: true
  token:
    description: Your API token
    required: true
  endpoint:
    description: Specify the QuantCDN API endpoint
    required: false
    default: https://api.quantcdn.io
  operation:
    description: The search operation to perform
    required: true
  path:
    description: The path on disk to JSON files to index, or URL path to remove
runs:
  using: "composite"
  steps:
    - name: Index/Unindex operation
      if: ${{ inputs.operation == 'index' || inputs.operation == 'unindex' }}
      uses: "docker://quantcdn/cli:2.0.0"
      with:
        entrypoint: quant
        args: search ${{ inputs.operation }} --clientid=${{ inputs.customer }} --token=${{ inputs.token }} --project=${{ inputs.project }} --endpoint=${{ inputs.endpoint }} --path="${{ inputs.path }}"
    - name: Status/Clear operation
      if: ${{ inputs.operation == 'status' || inputs.operation == 'clear' }}
      uses: "docker://quantcdn/cli:2.0.0"
      with:
        entrypoint: quant
        args: search ${{ inputs.operation }} --clientid=${{ inputs.customer }} --token=${{ inputs.token }} --project=${{ inputs.project }} --endpoint=${{ inputs.endpoint }}

branding:
  icon: "search"
  color: "blue"
